name = "proxy"
main = "build/worker/shim.mjs"
compatibility_date = "2023-08-23"
workers_dev = false
preview_urls = false

routes = [
  { pattern = "proxy.exbal.my.id", custom_domain = true }
]

[[kv_namespaces]]
binding = "SIREN"
id = "c506a2aba1244cd2ba6c794a135a788e"

[build]
command = "cargo install worker-build && worker-build --release"

[env.dev]
build = { command = "cargo install worker-build && worker-build --dev" }

[vars]
UUID = "f282b878-8711-45a1-8c69-5564172123c1"
MAIN_PAGE_URL = "https://raw.githubusercontent.com/FoolVPN-ID/Siren/refs/heads/master/web/index.html"
SUB_PAGE_URL = "https://raw.githubusercontent.com/FoolVPN-ID/Siren/refs/heads/master/web/sub.html"

[unsafe.metadata.observability]
enabled = true

[observability.logs]
enabled = true
